export const HOME = '/home'
export const LANDING = '/'
export const SIGN_IN='/signin'
export const SIGN_UP='/signup'
export const EMPLOYEES='/employees'
export const CUSTOMERS='/customers'
export const JOBS='/jobs'